# Generated by Django 5.2.9 on 2026-03-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student_registered',
            field=models.BooleanField(default=False),
        ),
    ]
