# Generated by Django 5.2.9 on 2026-03-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
