# Generated by Django 5.2.9 on 2026-03-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
