# Generated by Django 5.2.9 on 2026-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_payment_payment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default='', upload_to='projects/'),
            preserve_default=False,
        ),
    ]
