# Generated by Django 6.0.1 on 2026-03-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0008_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
