# Generated by Django 6.0.1 on 2026-03-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0011_alter_project_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
    ]
